export const SET_USERS = 'SET_USERS';
export const SET_FAVOURITES = 'ADD_TO_FAVOURITES';
export const ADD_NEW_USER = 'ADD_NEW_USER';
export const ADD_USER_TO_FAVOURITES = 'ADD_USER_TO_FAVOURITES';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_FROM_FAVOURITES = 'DELETE_USER_FROM_FAVOURITES';

export const CHANGE_THEME = 'CHANGE_THEME';